### ISSUE TITLE
data portal not able to plot

### ISSUE THREAD

**Issue by robfatland** [cormorack/yodapy#102]
I tried multiple attempts: Shallow profiler pod and platform; everything comes back "No Data available; please try again". This was for Axial, Oregon Offshore and Oregon Slope Base. Temperature: nope; DO: nope. Appears significant.

**Comment by lsetiawan** [comment]
This should be an issue on the io2_portal repo, not yodapy. Anyways, I checked on the data availability and I see no data since the 10th of June. This is why you're getting the No Data Available. I tried plotting on the OOI Data Portal and get the same thing. This might be due to deployments? If you see that there is data available on a certain date, and you are not able to plot that date, please let me know. Otherwise, the system has no issue.
